name: Android Buildozer

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Cloud Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev libffi-dev uuid-dev tar lld libtinfo5 auto-apt-proxy
        pip install --upgrade pip
        pip install buildozer cython virtualenv kivy

    - name: Build Android APK
      # شيلنا أمر yes تماماً واستخدمنا عزل البيئة عشان يشتغل صامت ويعدي كود 100
      run: |
        buildozer android debug --no-interaction
        
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: VideoFX-Android-APK
        path: bin/*.apk
